<div class="p-6 max-w-3xl mx-auto">
    <div class="mb-6">
        <flux:button href="{{ route('contacts.index') }}" icon="arrow-left" variant="ghost">
            Back to Contacts
        </flux:button>
    </div>

    <div class="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg shadow-sm p-8">
        <h1 class="text-2xl font-bold text-gray-900 dark:text-white mb-4">Two-Factor Authentication</h1>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
            Secure your account by requiring a verification code in addition to your password.
        </p>

        @if (session('status'))
            <div class="mb-6 p-4 bg-green-50 border border-green-200 text-green-800 rounded-lg">
                {{ session('status') }}
            </div>
        @endif

        <div class="space-y-6">
            @if ($enabled)
                <div class="bg-green-50 dark:bg-green-900/40 border border-green-200 dark:border-green-700 rounded-lg p-6">
                    <h2 class="text-lg font-semibold text-green-800 dark:text-green-200 mb-2">Two-factor authentication is enabled</h2>
                    <p class="text-sm text-green-700 dark:text-green-300">You will be asked for a verification code every time you sign in.</p>
                </div>

                <div class="flex justify-end">
                    <flux:button wire:click="disable" variant="danger">
                        Disable Two-Factor Authentication
                    </flux:button>
                </div>
            @else
                <div class="grid gap-6 md:grid-cols-2">
                    <div>
                        <h2 class="text-lg font-semibold text-gray-900 dark:text-white mb-3">Set up your authenticator app</h2>
                        <ol class="list-decimal list-inside space-y-2 text-sm text-gray-600 dark:text-gray-400">
                            <li>Download an authenticator app like Google Authenticator or Authy</li>
                            <li>Scan the QR code on the right</li>
                            <li>Enter the six-digit code generated by the app</li>
                        </ol>

                        <div class="mt-4 bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg p-4">
                            <p class="text-sm text-gray-600 dark:text-gray-400">Secret key for manual entry:</p>
                            <p class="mt-2 font-mono text-sm text-gray-900 dark:text-white break-all">{{ $secret }}</p>
                        </div>
                    </div>

                    <div class="flex flex-col items-center">
                        <div class="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg p-4 shadow-sm">
                            <img src="https://chart.googleapis.com/chart?chs=200x200&chld=M|0&cht=qr&chl={{ urlencode($qrCodeUrl) }}" alt="QR Code" class="w-48 h-48">
                        </div>
                    </div>
                </div>

                <form wire:submit.prevent="enable" class="mt-6">
                    <flux:input
                        wire:model.defer="code"
                        label="Enter the 6-digit code"
                        placeholder="000000"
                        maxlength="6"
                        class="md:w-1/2"
                    />
                    <x-input-error :messages="$errors->get('code')" class="mt-2" />

                    <div class="mt-4 flex justify-end">
                        <flux:button type="submit" variant="primary">
                            Enable Two-Factor Authentication
                        </flux:button>
                    </div>
                </form>
            @endif
        </div>
    </div>
</div>
